In [38]:
from sklearn.datasets import load_iris

iris = load_iris()

X = iris.data
y = iris.target

X.shape, y.shape

((150, 4), (150,))

In [39]:
from torch.utils import data
import torch

In [40]:
X = torch.from_numpy(X)
y = torch.from_numpy(y)

In [41]:
dataset = data.TensorDataset(X, y)
data_loader = data.DataLoader(dataset, batch_size=10, shuffle=True)

In [43]:
for X_train, y_train in data_loader:
    print(X_train)
    print(y_train)

tensor([[5.9000, 3.2000, 4.8000, 1.8000],
        [5.0000, 3.6000, 1.4000, 0.2000],
        [6.8000, 3.0000, 5.5000, 2.1000],
        [5.6000, 3.0000, 4.5000, 1.5000],
        [5.0000, 2.0000, 3.5000, 1.0000],
        [4.6000, 3.6000, 1.0000, 0.2000],
        [5.6000, 3.0000, 4.1000, 1.3000],
        [6.5000, 3.0000, 5.5000, 1.8000],
        [5.2000, 3.4000, 1.4000, 0.2000],
        [6.1000, 2.8000, 4.0000, 1.3000]], dtype=torch.float64)
tensor([1, 0, 2, 1, 1, 0, 1, 2, 0, 1])
tensor([[6.4000, 3.2000, 5.3000, 2.3000],
        [5.5000, 2.4000, 3.7000, 1.0000],
        [6.3000, 2.5000, 5.0000, 1.9000],
        [6.3000, 3.4000, 5.6000, 2.4000],
        [6.3000, 2.3000, 4.4000, 1.3000],
        [6.0000, 2.9000, 4.5000, 1.5000],
        [5.6000, 2.8000, 4.9000, 2.0000],
        [5.5000, 2.5000, 4.0000, 1.3000],
        [6.3000, 2.9000, 5.6000, 1.8000],
        [6.3000, 2.8000, 5.1000, 1.5000]], dtype=torch.float64)
tensor([2, 1, 2, 2, 1, 1, 2, 1, 2, 2])
tensor([[5.2000, 4.1000, 1.5000, 0.100