In [13]:
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

batch_size, num_steps = 32, 35
train_iter, vocab = d2l.load_data_time_machine(batch_size, num_steps)

In [14]:
for X, y in train_iter:
    print(X[:1, :12])
    print('---------------------------------------------------')
    print(y[:1, :12])
    print('.......................................................')

torch.Size([32, 35])
tensor([[ 1,  3,  5, 13,  2,  1, 13,  4, 15,  9,  5,  6]])
---------------------------------------------------
tensor([[ 3,  5, 13,  2,  1, 13,  4, 15,  9,  5,  6,  2]])
.......................................................
torch.Size([32, 35])
tensor([[ 1,  3, 10,  4, 22,  2, 12, 12,  2, 10,  1, 16]])
---------------------------------------------------
tensor([[ 3, 10,  4, 22,  2, 12, 12,  2, 10,  1, 16,  7]])
.......................................................
torch.Size([32, 35])
tensor([[ 5,  2,  6,  3,  1,  3,  7,  1,  8, 20,  2,  4]])
---------------------------------------------------
tensor([[ 2,  6,  3,  1,  3,  7,  1,  8, 20,  2,  4, 23]])
.......................................................
torch.Size([32, 35])
tensor([[ 4,  1, 10,  2, 15,  7,  6, 11,  5,  3,  2,  1]])
---------------------------------------------------
tensor([[ 1, 10,  2, 15,  7,  6, 11,  5,  3,  2,  1, 13]])
.......................................................
torch.Size([

In [15]:
len(vocab)

28