## 2D 池化层

In [38]:
import torch
from torch import nn
from d2l import torch as d2l

def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i: i + p_h, j: j + p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i: i + p_h, j: j + p_w].mean()
    return Y

## 验证 2D 最大池化层

In [39]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

## 使用 PyTorch 的池化层 nn.MaxPoll2d

In [40]:
X = torch.arange(36, dtype=torch.float32).reshape((1, 1, 6, 6))

In [41]:
X

tensor([[[[ 0.,  1.,  2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9., 10., 11.],
          [12., 13., 14., 15., 16., 17.],
          [18., 19., 20., 21., 22., 23.],
          [24., 25., 26., 27., 28., 29.],
          [30., 31., 32., 33., 34., 35.]]]])

In [42]:
# 深度学习框架中的 窗口大小 = 步幅大小
pool2d = nn.MaxPool2d(3)
pool2d(X)

tensor([[[[14., 17.],
          [32., 35.]]]])

## 指定 窗口大小; 步幅; 填充

In [43]:
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))
pool2d = nn.MaxPool2d(kernel_size=(2, 3), padding=(1, 1), stride=(2, 3))
pool2d(X), X.shape

(tensor([[[[ 1.,  3.],
           [ 9., 11.],
           [13., 15.]]]]),
 torch.Size([1, 1, 4, 4]))

## 池化层在每个输入通道上单独运算

In [49]:
# X.shape 批量大小, 通道数量, 图像高, 宽
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))
X = torch.cat((X, X+1), 1)
X.shape

torch.Size([1, 2, 4, 4])

In [50]:
pool2d(X), pool2d(X).shape

(tensor([[[[ 5.,  7.],
           [13., 15.]],
 
          [[ 6.,  8.],
           [14., 16.]]]]),
 torch.Size([1, 2, 2, 2]))