# dropout

In [38]:
import torch

In [39]:
dropout = 0.4
X = torch.tensor([i for i in range(9)]).reshape(3, 3)
X.shape

torch.Size([3, 3])

In [40]:
mask = (torch.rand(X.shape) > dropout).float()
mask

tensor([[1., 1., 1.],
        [1., 0., 0.],
        [1., 1., 0.]])

In [41]:
torch.rand(X.shape)

tensor([[0.4972, 0.1856, 0.7533],
        [0.0237, 0.3123, 0.8152],
        [0.5135, 0.4410, 0.6793]])

In [42]:
mask_test = (torch.rand(X.shape) > dropout)
mask_test

tensor([[ True,  True,  True],
        [ True, False, False],
        [False, False,  True]])

In [43]:
mask_test.float()

tensor([[1., 1., 1.],
        [1., 0., 0.],
        [0., 0., 1.]])